spring.application.name=TemplateService
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5433/TemplateService?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=1313
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database=postgresql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect

template.classpath=classpath:
template.dir=classpath:template/
data.output.pdf=D:/Idea/TemplateService/TemplateService/pdfs

logging.level.net.sf.jasperreports=DEBUG